services:
  isostack:
    image: kloudyman/isostack:latest
    container_name: isostack
    restart: unless-stopped
    ports:
      - "8585:8000"
    volumes:
      - ./data/isos:/data/isos
      - isostack-db:/data
    environment:
      - BASE_URL=http://localhost:8585
      - MAX_CONCURRENT_DOWNLOADS=3
      - ISO_STORAGE_PATH=/data/isos
      - DB_PATH=/data/db.sqlite

volumes:
  isostack-db:
